#!/bin/bash

### BEGIN INIT INFO
# Provides: streamingclient
# Required-Start:
# Required-Stop: $network $remote_fs $syslog
# Default-Start: S
# Default-Stop: 0 1 6
# Should-Start: default
# Should-Stop: autofs
# Short-Description: StreamingClient Boot Script
# Description: StreamingClient Boot Script
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
#PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="StreamingClient Boot Script"
NAME=StreamingClientBoot
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/aa-$NAME

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
/etc/vectra130/bin/StreamingClient -b -d
return $?
}

do_stop()
{
killall StreamingClient
return $?
}

#
# Function that sends a SIGHUP to the daemon/service
#
VERBOSE="yes"
case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop}"
	exit 3
	;;
esac

:
