#!/bin/bash
# v2.0 raspi

#nur einmal ausfuehren!
[ $(pidof -x $(basename $0) | wc -w) -gt 2 ] && exit 0

#Shutdown VOR-Script
#Wird anstatt des init scripts ausgefuehrt

ACTION=$0
ACTION=$(basename $ACTION)
ACTION2="$@"


stopStreamingClient(){
	echo suspend > /tmp/.frontendStatus
	while [ $(pidof -xs vdr | wc -w) == 1 ]; do
	    sleep 1
	done
	while [ $(pidof -xs kodi.bin | wc -w) == 1 ]; do
	    sleep 1
	done
	systemctl stop streamingclient.service
}

saveSyslog(){
	cp /var/log/syslog /etc/vectra130/lastSyslog
}

showscreeninfo(){
        killall -9 -q showscreenimage.sh
	tput -Tlinux clear > /dev/tty2
        /etc/vectra130/scripts/showscreenimage.sh $IMG &
        sleep 3
}

logger -t "*"POWEROFF "'$ACTION $ACTION2' wird eingeleitet"

case "$ACTION" in
reboot)
	/sbin/shutdown.exec -r now
	;;
poweroff)
	/sbin/shutdown.exec -h -P now
	;;
shutdown)
	/sbin/shutdown.exec $ACTION2
	;;
init)
	case $@ in
	  0)
		echo -e "\e[33mSystem geht in Standby\e[0m"
		echo suspend > /tmp/.frontendStatus
		exit 0
	  ;;
	  6)
		echo -e "\e[33mSystem geht in Standby\e[0m"
		echo suspend > /tmp/.frontendStatus
		exit 0
	  ;;
	  reboot)
		IMG=reboot
		touch /tmp/.poweroff
		stopStreamingClient
		showscreeninfo
		saveSyslog
		/sbin/raspi-init 6
		exit 0
	  ;;
	  poweroff)
		IMG=ausschalten
		touch /tmp/.poweroff
		stopStreamingClient
		showscreeninfo
		saveSyslog
		/sbin/raspi-init 0
		exit 0
	  ;;
	  *)
		echo -e "\e[33musage: init [0|6|poweroff|reboot]\e[0m"
		logger -t "*"SHUTDOWN "\'$ACTION $ACTION2\' abgebrochen!!!"
	  ;;
	esac
	;;
esac
